### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by fkztw** [M157q/2dg#1]
- [x] http://2d-gate.org/thread-13303-1-4.html#.WCYPTXc8XBI
- [x] http://2d-gate.org/thread-12270-1-5.html#.WCYPdXc8XBI
- [x] http://2d-gate.org/thread-11654-1-6.html#.WCYPunc8XBI
- [x] http://2d-gate.org/thread-11653-1-6.html#.WCYPu3c8XBI
    - `$ is not a function` sometimes 
        - https://github.com/tjjh89017/2dg/pull/10
- [x] http://2d-gate.org/thread-11327-1-6.html#.WCYPvnc8XBI
- [x] http://2d-gate.org/thread-12885-1-6.html#.WCYPwHc8XBI
    - only 1 episode
        - https://github.com/tjjh89017/2dg/pull/7
- [x] http://2d-gate.org/thread-11328-1-6.html#.WCYPwnc8XBI
    - only 1 episode
- [x] http://2d-gate.org/thread-13318-1-7.html#.WCYP8Hc8XBI
- [x] http://2d-gate.org/thread-12410-1-7.html#.WCYP7Xc8XBI
- [x] http://2d-gate.org/thread-10560-1-6.html#.WCYP43c8XBI
- [x] http://2d-gate.org/thread-11266-1-6.html#.WCYPxHc8XBI
- [x] http://2d-gate.org/thread-12896-1-11.html#.WCYQlHc8XBI
    - `$ is not a function` sometimes 
- [x] http://2d-gate.org/thread-12261-1-11.html#.WCbxf3c8XOR
    - only 1 episode
- [x] http://2d-gate.org/thread-12140-1-13.html#.WCYQvXc8XBI
    - only 1 episode
- [x] http://2d-gate.org/thread-11531-1-12.html#.WCYQuHc8XBI
    - 數碼寶貝大冒險 日配 第 30 集壞了，需要 error handling。
    - https://github.com/M157q/2dg/issues/1#issuecomment-260760660
        - https://github.com/tjjh89017/2dg/pull/9

**Comment by M157q** [comment]
```
/home/m157q/github/2dg/index.js:31          
        var code = $("script").last().text()
                   ^
                              
TypeError: $ is not a function                                
    at Object.callback (/home/m157q/github/2dg/index.js:31:20)                               
    at Crawler._onContent (/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:461:17)
    at Request._callback (/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:351:18)                     
    at Request.self.callback (/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:236:22)
    at emitTwo (events.js:106:13)    
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:1142:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:1096:12)
```

**Comment by M157q** [comment]
```
$ node index.js "http://2d-gate.org/thread-12885-1-6.html#.WCYPwHc8XBI"
/home/m157q/github/2dg/index.js:82
        anime_name = (name[1] == undefined ? '' : name[1].trim())
                          ^

TypeError: Cannot read property '1' of null
    at Object.callback (/home/m157q/github/2dg/index.js:82:27)
    at Crawler._onInject (/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:469:13)
    at /home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:458:18
    at Crawler._inject (/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:147:9)
    at Crawler._onContent (/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:457:14)
    at Request._callback (/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:351:18)
    at Request.self.callback (/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:236:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:1142:14)
```

**Comment by fkztw** [comment]
```
$ node index.js "http://2d-gate.org/thread-13318-1-7.html#.WCYP8Hc8XBI"
/home/m157q/github/2dg/index.js:31
        var code = $("script").last().text()
                   ^

TypeError: $ is not a function
    at Object.callback (/home/m157q/github/2dg/index.js:31:20)
    at Crawler._onContent (/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:461:17)
    at Request._callback (/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:351:18)
    at Request.self.callback (/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:236:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:1142:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:1096:12)
```

**Comment by fkztw** [comment]
Maybe we need to wait until the jQuery loaded.

**Comment by fkztw** [comment]
```
$ node index.js "http://2d-gate.org/thread-11531-1-12.html#.WCYQuHc8XBI"
數碼寶貝大冒險 (S1) [[email protected]/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */@繁][01~54][End]
[ '數碼寶貝大冒險 (S1) [[email protected]/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName(\'script\'),e=t.length;e--;)if(t[e].getAttribute(\'data-cfhash\'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute(\'data-cfemail\')){for(e=\'\',r=\'0x\'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+=\'%\'+(\'0\'+(\'0x\'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */@繁][01~54][End]',
  '數碼寶貝大冒險 (S1) ',
  '[01~54][End]',
  index: 0,
  input: '數碼寶貝大冒險 (S1) [[email protected]/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName(\'script\'),e=t.length;e--;)if(t[e].getAttribute(\'data-cfhash\'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute(\'data-cfemail\')){for(e=\'\',r=\'0x\'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+=\'%\'+(\'0\'+(\'0x\'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */@繁][01~54][End]' ]
[數碼寶貝大冒險 (S1)][01~54][End] - 05  [#                                                 ] 2% 360.153 sec 681.60 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 04  [#                                                 ] 2% 381.253 sec 649.50 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 08  [#                                                 ] 3% 227.174 sec 941.19 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 09  [#                                                 ] 1% 498.154 sec 456.99 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 01  [#                                                 ] 1% 518.711 sec 423.90 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 15  [#                                                 ] 2% 274.628 sec 826.09 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 16  [                                                  ] 1% 774.946 sec 318.20 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 11  [                                                  ] 1% 779.867 sec 306.26 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 02  [                                                  ] 0% 1415.549 sec 160.98 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 19  [                                                  ] 1% 736.569 sec 286.74 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 18  [                                                  ] 0% 1163.525 sec 201.94 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 17  [                                                  ] 0% 1951.409 sec 128.96 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 06  [                                                  ] 0% 1483.37 sec 160.07 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 13  [                                                  ] 0% 1126.594 sec 206.29 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 14  [                                                  ] 0% 2113.931 sec 109.21 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 22  [                                                  ] 0% 3076.064 sec 74.14 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 20  [                                                  ] 0% 3165.147 sec 74.59 kB/s
[數碼寶貝大冒險 (S1)][01~54][End] - 24  [                                                  ] 0% null sec 0.00 kB/s
/home/m157q/github/2dg/index.js:45
        var type = /.*\/(.*)/.exec(url.type)[1]
                                      ^

TypeError: Cannot read property 'type' of undefined
    at Object.callback (/home/m157q/github/2dg/index.js:45:39)
    at Crawler._onInject (/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:469:13)
    at /home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:458:18
    at Crawler._inject (/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:147:9)
    at Crawler._onContent (/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:457:14)
    at Request._callback (/home/m157q/github/2dg/node_modules/crawler/lib/crawler.js:351:18)
    at Request.self.callback (/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:236:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/m157q/github/2dg/node_modules/crawler/node_modules/request/request.js:1142:14)
```

**Comment by fkztw** [comment]
- https://github.com/tjjh89017/2dg/pull/4
- https://github.com/tjjh89017/2dg/pull/5
- https://github.com/tjjh89017/2dg/pull/6
